#' Get Gene Correlation Data
#'
#' Obtain correlation data by querying MySQL database
#'
#' @param Sample_Type Type of RNA Seq samples used to create correlation data.
#' Either "all", "normal", or "cancer". Can be a single value for all genes,
#' or a vector corresponding to geneList. Not used if corrMat is set.
#' @param Tissue Which tissue type should gene correlations be derived from?
#' Default = "all". Can be a single value for all genes,
#' or a vector corresponding to geneList. Not used if corrMat is set.
#' Run getTissueTypes() to see available tissue list.
#' @param geneList Vector of genes for which data will be extracted.
#' @param corrMat A custom correlation matrix generated by generateCorrelations()
#' to use instead of pre-supplied databases.
#' @param pool an object created by pool::dbPool to accessing SQL database.
#' It will be created if not supplied. Not used if corrMat is set.
#' @return A correlation data frame object
#'
#' @examples
#'correlationAnalyzeR::getCorrelationData(Sample_Type = "normal",
#'                                        Tissue = "kidney",
#'                                        geneList = c("ATM", "BRCA1"))
#'
#' @export
getCorrelationData <- function(Sample_Type,
                               Tissue, geneList,
                               corrMat = NULL,
                               pool = NULL) {

  # Species = "hsapiens"
  # Sample_Type = "all"
  # Tissue = c("female_reproductive")
  # geneList = c("BRCA1")
  # pool = NULL

  # Use the user-supplied corrMat if provided
  if (! is.null(corrMat)) {
    resdf <- as.data.frame(corrMat[, geneList])
    colnames(resdf) <- geneList
    return(resdf)
  }

  Species <- "hsapiens"

  if (! is.null(pool)) {
    if (! pool$valid) {
      pool <- NULL
    } else {
      conn <- pool::poolCheckout(pool)
      doPool <- TRUE
      on.exit(pool::poolReturn(conn))
    }
  }

  if (is.null(pool)) {
    doPool <- FALSE
    conn <- NULL
    retryCounter <- 1
    # cat("\nEstablishing connection to database ... \n")
    while(is.null(conn)) {
      conn <- try(silent = T, eval({
        DBI::dbConnect(
          drv = RMySQL::MySQL(),
          user = "public-rds-user@m2600az-db01p.mysql.database.azure.com", port = 3306,
          dbname="correlation_analyzer",
          password='public-user-password',
          host="m2600az-db01p.mysql.database.azure.com"
        )
      }))
      if ("try-error" %in% class(conn)) {
        if (retryCounter == 3) {
          stop("Unable to connect to database. Check internet connection and please contanct",
               " package maintainer if you believe this is an error.")
        }
        warning(paste0("Failed to establish connection to database ... retrying now ... ",
                       (4-retryCounter), " attempts left."),
                immediate. = T)
        conn <- NULL
        retryCounter <- retryCounter + 1
        Sys.sleep(1)
      }
    }
    on.exit(DBI::dbDisconnect(conn))
  }

  # Make sure all tissue entries are appropriate
  goodConditions <- getTissueTypes(#Species = Species,
                                   pool = pool)

  goodTissues <- unique(gsub(goodConditions,
                             pattern = "(.*) - (.*)",
                             replacement = "\\1"))
  goodSamples <- unique(gsub(goodConditions,
                             pattern = "(.*) - (.*)",
                             replacement = "\\2"))

  if (! all(Sample_Type %in% goodSamples)) {
    stop("Sample type must be either 'normal' or 'cancer'")
  } else if (! all(Tissue %in% goodTissues)) {
    stop("Tissue types must be selected from available options.",
         " Run correlationAnalyzeR::getTissueTypes() to see available tissue - sample groups.")
  }

  geneNames <- correlationAnalyzeR::hsapiens_corrSmall_geneNames
  # Queries from multiple db at once
  if (length(Tissue) == 1) {
    Tissue <- rep(Tissue, length(geneList))
  } else if (length(Tissue) > 1) {
    if (length(Tissue) != length(geneList)) {
      warning("Number of valid genes not equal
           to length of supplied Tissue vector. Using only ", Tissue[1])
      Tissue <- rep(Tissue[1], length(geneList))
    }
  }
  if (length(Sample_Type) == 1) {
    Sample_Type <- rep(Sample_Type, length(geneList))
  } else if (length(Sample_Type) > 1) {
    if (length(Sample_Type) != length(geneList)) {
      warning("Number of valid genes not equal
           to length of supplied Sample_Type vector. Using only ", Sample_Type[1])
      Sample_Type <- rep(Sample_Type[1], length(geneList))
    }
  }

  if (length(unique(Tissue)) == 1 & length(unique(Sample_Type)) == 1) {
    sql <- paste0("SELECT * FROM correlations_",
                  Species, "_",
                  tolower(unique(Sample_Type)), "_",
                  tolower(unique(Tissue)),
                  " WHERE row_names IN ('",
                  paste(geneList, collapse = "','"), "')")
    resdf <- try(silent = T, eval({
      DBI::dbGetQuery(conn, sql)
    }))
    if ("try-error" %in% class(resdf)) {
      stop("ERROR IN DB CONNECTION: ", resdf)
    }
    resdf2 <- stringr::str_split_fixed(resdf$values, stringr::fixed(","), n = Inf)
    resdf2 <- apply(t(resdf2), 1:2, as.numeric)
    resdf2 <- as.data.frame(resdf2)
    colnames(resdf2) <- resdf$row_names
    rownames(resdf2) <- geneNames
    if (length(geneList) > 1) {
      resdf2 <- resdf2[,order(match(colnames(resdf2), geneList))]
    }
  } else {
    resDfList <- list()
    for ( i in 1:length(geneList) ) {
      geneName <- geneList[i]
      TissueNow <- Tissue[i]
      Sample_TypeNow <- Sample_Type[i]
      sql <- paste0("SELECT * FROM correlations_",
                    Species, "_",
                    tolower(Sample_TypeNow), "_", tolower(TissueNow),
                    " WHERE row_names IN ('",
                    geneName, "')")
      resdf <- try(silent = T, eval({
        DBI::dbGetQuery(conn, sql)
      }))
      if ("try-error" %in% class(resdf)) {
        stop("ERROR IN DB CONNECTION: ", resdf)
      }
      resdf2 <- stringr::str_split_fixed(resdf$values, stringr::fixed(","), n = Inf)
      resdf2 <- apply(t(resdf2), 1:2, as.numeric)
      resdf2 <- as.data.frame(resdf2)
      colnames(resdf2) <- resdf$row_names
      rownames(resdf2) <- geneNames
      resDfList[[i]] <- resdf2
    }
    resdf2 <- dplyr::bind_cols(resDfList)
    rownames(resdf2) <- geneNames
  }
  return(resdf2)
}

